version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: mangalith-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mangalith}
      POSTGRES_USER: ${POSTGRES_USER:-mangalith}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mangalith123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mangalith-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mangalith} -d ${POSTGRES_DB:-mangalith}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


volumes:
  postgres_data:
    driver: local

networks:
  mangalith-network:
    driver: bridge