services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    container_name: mangalith-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mangalith_dev}
      POSTGRES_USER: ${POSTGRES_USER:-mangalith_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mangalith-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mangalith_user} -d ${POSTGRES_DB:-mangalith_dev}"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  mangalith-network:
    driver: bridge
