### File Upload Test
POST {{host}}/api/files/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="sample.cbr"
Content-Type: application/x-rar-compressed

< ./test-files/sample.cbr
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

Test Manga Title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

This is a test manga upload
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Get File
GET {{host}}/api/files/{{fileId}}
Authorization: Bearer {{token}}

### Delete File
DELETE {{host}}/api/files/{{fileId}}
Authorization: Bearer {{token}}

### Variables
@host = http://localhost:5000
@token = your-jwt-token-here
@fileId = file-id-from-upload-response